// user actions
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const UPDATE_WALLET_CONNECTED = 'UPDATE_WALLET_CONNECTED'
export const UPDATE_BALANCE = 'UPDATE_BALANCE'
