import Head from 'next/head'
import { useEffect } from 'react'
import { HomeStyled } from '@/styles/pages/Home.styled'
import { connect } from 'react-redux'
import { getData } from '@/store/actions/homeActions'
import TopSection from '@/components/home/TopSection'
import ContractStats from '@/components/home/ContractStats'


const Home = ({ data, getData }: any) => {
  useEffect(() => {
    getData();
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeStyled>
        {Object.keys(data).length && (
          <>
            <TopSection data={data} />
            <ContractStats data={data} />
          </>
        )}
      </HomeStyled>
    </>
  )
}

const mapStateToProps = (state: any) => {
  return {
    data: state.home.homeItems
  }
}

export default connect(mapStateToProps, { getData })(Home)
