import Head from 'next/head'
import { HomeStyled } from '@/styles/pages/Home.styled'
import { connect } from 'react-redux'


const Home = ({ user }: any) => {
  console.log(user);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeStyled>
        <h1>Home</h1>
      </HomeStyled>
    </>
  )
}

const mapStateToProps = (state: any) => {
  return {
    user: state.auth.user
  }
}

export default connect(mapStateToProps)(Home)
